// Single source of truth for API path strings — mirrors API.md.
export const ENDPOINTS = {
  login: "/auth/login",
  refresh: "/auth/refresh",
  logout: "/auth/logout",
  me: "/auth/me",
  anonymousTokens: "/anonymous-tokens",
  evidence: "/evidence",
  complaints: "/complaints",
  complaintStatus: (id) => `/complaints/${id}/status`,
  strikeState: "/dashboard/strike-state",
  sos: "/sos",
  sosActive: "/sos/active",
  sosAcknowledge: (id) => `/sos/${id}/acknowledge`,
  sosResolve: (id) => `/sos/${id}/resolve`,
  seatStudentBatch: "/seat-students/batch",
  seatStudentGet: (batchId) => `/seat-students/${batchId}`,
  seatPlans: "/seat-plans",
  seatPlanGet: (id) => `/seat-plans/${id}`,
  ledgerEntries: "/ledger/entries",
  ledgerSummary: "/ledger/summary",
  foodCatalog: "/food-catalog",
  syllabusSummarize: "/syllabus/summarize",
  syllabusFilter: "/syllabus/filter",
  syllabusStudyPlan: "/syllabus/study-plan",
  factCheckSearch: "/fact-check/search",
  factCheckVerify: "/fact-check/verify",
};
